# Generated by Django 5.1.7 on 2025-03-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='user_session',
        ),
    ]
