# Generated by Django 5.1.7 on 2025-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_alter_usersession_options_alter_usersession_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
