# Generated by Django 5.1.7 on 2025-04-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album_id', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='songs/')),
                ('image', models.FileField(null=True, upload_to='songs/image/')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'db_table': 'song',
            },
        ),
    ]
