# Generated by Django 5.1.7 on 2025-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('groups', models.ManyToManyField(blank=True, related_name='artist_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='artist_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Nghệ sĩ',
                'verbose_name_plural': 'Danh sách nghệ sĩ',
                'ordering': ['name'],
            },
        ),
    ]
